version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto-certs:/mosquitto/config/certs

