version: '3.7'

services:
  mosquitto:
    build: .
    container_name: mosquitto_tls
    ports:
      - "8883:8883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./certs:/mosquitto/certs
    restart: unless-stopped

